[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
evm_version = "cancun"
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 200
via_ir = true

[profile.default.fuzz]
runs = 256

[profile.intense.fuzz]
runs = 10_000

[rpc_endpoints]
sepolia = "${RPC_SEPOLIA}"
mainnet = "${RPC_MAINNET}"
polygon = "${RPC_POLYGON}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }